# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/sheets/sheets_addon_manifest.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/apps/script/type/extension_point_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/apps/script/type/sheets/sheets_addon_manifest.proto", :syntax => :proto3) do
    add_message "google.apps.script.type.sheets.SheetsAddOnManifest" do
      optional :homepage_trigger, :message, 3, "google.apps.script.type.HomepageExtensionPoint"
      optional :on_file_scope_granted_trigger, :message, 5, "google.apps.script.type.sheets.SheetsExtensionPoint"
    end
    add_message "google.apps.script.type.sheets.SheetsExtensionPoint" do
      optional :run_function, :string, 1
    end
  end
end

module Google
  module Apps
    module Script
      module Type
        module Sheets
          SheetsAddOnManifest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.sheets.SheetsAddOnManifest").msgclass
          SheetsExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.sheets.SheetsExtensionPoint").msgclass
        end
      end
    end
  end
end
