# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/sheets/sheets_addon_manifest.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/apps/script/type/extension_point_pb'


descriptor_data = "\n:google/apps/script/type/sheets/sheets_addon_manifest.proto\x12\x1egoogle.apps.script.type.sheets\x1a\x1fgoogle/api/field_behavior.proto\x1a-google/apps/script/type/extension_point.proto\"\xbd\x01\n\x13SheetsAddOnManifest\x12I\n\x10homepage_trigger\x18\x03 \x01(\x0b\x32/.google.apps.script.type.HomepageExtensionPoint\x12[\n\x1don_file_scope_granted_trigger\x18\x05 \x01(\x0b\x32\x34.google.apps.script.type.sheets.SheetsExtensionPoint\"1\n\x14SheetsExtensionPoint\x12\x19\n\x0crun_function\x18\x01 \x01(\tB\x03\xe0\x41\x02\x42\xe6\x01\n\"com.google.apps.script.type.sheetsB\x18SheetsAddOnManifestProtoP\x01Z=google.golang.org/genproto/googleapis/apps/script/type/sheets\xaa\x02\x1eGoogle.Apps.Script.Type.Sheets\xca\x02\x1eGoogle\\Apps\\Script\\Type\\Sheets\xea\x02\"Google::Apps::Script::Type::Sheetsb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.apps.script.type.HomepageExtensionPoint", "google/apps/script/type/extension_point.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Apps
    module Script
      module Type
        module Sheets
          SheetsAddOnManifest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.sheets.SheetsAddOnManifest").msgclass
          SheetsExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.sheets.SheetsExtensionPoint").msgclass
        end
      end
    end
  end
end
