# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/gmail/gmail_addon_manifest.proto

require 'google/protobuf'

require 'google/apps/script/type/addon_widget_set_pb'
require 'google/apps/script/type/extension_point_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/apps/script/type/gmail/gmail_addon_manifest.proto", :syntax => :proto3) do
    add_message "google.apps.script.type.gmail.GmailAddOnManifest" do
      optional :homepage_trigger, :message, 14, "google.apps.script.type.HomepageExtensionPoint"
      repeated :contextual_triggers, :message, 3, "google.apps.script.type.gmail.ContextualTrigger"
      repeated :universal_actions, :message, 4, "google.apps.script.type.gmail.UniversalAction"
      optional :compose_trigger, :message, 12, "google.apps.script.type.gmail.ComposeTrigger"
      optional :authorization_check_function, :string, 7
    end
    add_message "google.apps.script.type.gmail.UniversalAction" do
      optional :text, :string, 1
      oneof :action_type do
        optional :open_link, :string, 2
        optional :run_function, :string, 3
      end
    end
    add_message "google.apps.script.type.gmail.ComposeTrigger" do
      repeated :actions, :message, 5, "google.apps.script.type.MenuItemExtensionPoint"
      optional :draft_access, :enum, 4, "google.apps.script.type.gmail.ComposeTrigger.DraftAccess"
    end
    add_enum "google.apps.script.type.gmail.ComposeTrigger.DraftAccess" do
      value :UNSPECIFIED, 0
      value :NONE, 1
      value :METADATA, 2
    end
    add_message "google.apps.script.type.gmail.ContextualTrigger" do
      optional :on_trigger_function, :string, 4
      oneof :trigger do
        optional :unconditional, :message, 1, "google.apps.script.type.gmail.UnconditionalTrigger"
      end
    end
    add_message "google.apps.script.type.gmail.UnconditionalTrigger" do
    end
  end
end

module Google
  module Apps
    module Script
      module Type
        module Gmail
          GmailAddOnManifest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.gmail.GmailAddOnManifest").msgclass
          UniversalAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.gmail.UniversalAction").msgclass
          ComposeTrigger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.gmail.ComposeTrigger").msgclass
          ComposeTrigger::DraftAccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.gmail.ComposeTrigger.DraftAccess").enummodule
          ContextualTrigger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.gmail.ContextualTrigger").msgclass
          UnconditionalTrigger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.gmail.UnconditionalTrigger").msgclass
        end
      end
    end
  end
end
