# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/resource.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/api/resource.proto", :syntax => :proto3) do
    add_message "google.api.ResourceDescriptor" do
      optional :type, :string, 1
      repeated :pattern, :string, 2
      optional :name_field, :string, 3
      optional :history, :enum, 4, "google.api.ResourceDescriptor.History"
      optional :plural, :string, 5
      optional :singular, :string, 6
      repeated :style, :enum, 10, "google.api.ResourceDescriptor.Style"
    end
    add_enum "google.api.ResourceDescriptor.History" do
      value :HISTORY_UNSPECIFIED, 0
      value :ORIGINALLY_SINGLE_PATTERN, 1
      value :FUTURE_MULTI_PATTERN, 2
    end
    add_enum "google.api.ResourceDescriptor.Style" do
      value :STYLE_UNSPECIFIED, 0
      value :DECLARATIVE_FRIENDLY, 1
    end
    add_message "google.api.ResourceReference" do
      optional :type, :string, 1
      optional :child_type, :string, 2
    end
  end
end

module Google
  module Api
    ResourceDescriptor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.ResourceDescriptor").msgclass
    ResourceDescriptor::History = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.ResourceDescriptor.History").enummodule
    ResourceDescriptor::Style = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.ResourceDescriptor.Style").enummodule
    ResourceReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.ResourceReference").msgclass
  end
end
