# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/routing.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/api/routing.proto", :syntax => :proto3) do
    add_message "google.api.RoutingRule" do
      repeated :routing_parameters, :message, 2, "google.api.RoutingParameter"
    end
    add_message "google.api.RoutingParameter" do
      optional :field, :string, 1
      optional :path_template, :string, 2
    end
  end
end

module Google
  module Api
    RoutingRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.RoutingRule").msgclass
    RoutingParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.RoutingParameter").msgclass
  end
end
