# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/context/attribute_context.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/rpc/context/attribute_context.proto", :syntax => :proto3) do
    add_message "google.rpc.context.AttributeContext" do
      optional :origin, :message, 7, "google.rpc.context.AttributeContext.Peer"
      optional :source, :message, 1, "google.rpc.context.AttributeContext.Peer"
      optional :destination, :message, 2, "google.rpc.context.AttributeContext.Peer"
      optional :request, :message, 3, "google.rpc.context.AttributeContext.Request"
      optional :response, :message, 4, "google.rpc.context.AttributeContext.Response"
      optional :resource, :message, 5, "google.rpc.context.AttributeContext.Resource"
      optional :api, :message, 6, "google.rpc.context.AttributeContext.Api"
      repeated :extensions, :message, 8, "google.protobuf.Any"
    end
    add_message "google.rpc.context.AttributeContext.Peer" do
      optional :ip, :string, 1
      optional :port, :int64, 2
      map :labels, :string, :string, 6
      optional :principal, :string, 7
      optional :region_code, :string, 8
    end
    add_message "google.rpc.context.AttributeContext.Api" do
      optional :service, :string, 1
      optional :operation, :string, 2
      optional :protocol, :string, 3
      optional :version, :string, 4
    end
    add_message "google.rpc.context.AttributeContext.Auth" do
      optional :principal, :string, 1
      repeated :audiences, :string, 2
      optional :presenter, :string, 3
      optional :claims, :message, 4, "google.protobuf.Struct"
      repeated :access_levels, :string, 5
    end
    add_message "google.rpc.context.AttributeContext.Request" do
      optional :id, :string, 1
      optional :method, :string, 2
      map :headers, :string, :string, 3
      optional :path, :string, 4
      optional :host, :string, 5
      optional :scheme, :string, 6
      optional :query, :string, 7
      optional :time, :message, 9, "google.protobuf.Timestamp"
      optional :size, :int64, 10
      optional :protocol, :string, 11
      optional :reason, :string, 12
      optional :auth, :message, 13, "google.rpc.context.AttributeContext.Auth"
    end
    add_message "google.rpc.context.AttributeContext.Response" do
      optional :code, :int64, 1
      optional :size, :int64, 2
      map :headers, :string, :string, 3
      optional :time, :message, 4, "google.protobuf.Timestamp"
      optional :backend_latency, :message, 5, "google.protobuf.Duration"
    end
    add_message "google.rpc.context.AttributeContext.Resource" do
      optional :service, :string, 1
      optional :name, :string, 2
      optional :type, :string, 3
      map :labels, :string, :string, 4
      optional :uid, :string, 5
      map :annotations, :string, :string, 6
      optional :display_name, :string, 7
      optional :create_time, :message, 8, "google.protobuf.Timestamp"
      optional :update_time, :message, 9, "google.protobuf.Timestamp"
      optional :delete_time, :message, 10, "google.protobuf.Timestamp"
      optional :etag, :string, 11
      optional :location, :string, 12
    end
  end
end

module Google
  module Rpc
    module Context
      AttributeContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext").msgclass
      AttributeContext::Peer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext.Peer").msgclass
      AttributeContext::Api = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext.Api").msgclass
      AttributeContext::Auth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext.Auth").msgclass
      AttributeContext::Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext.Request").msgclass
      AttributeContext::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext.Response").msgclass
      AttributeContext::Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AttributeContext.Resource").msgclass
    end
  end
end
