# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/context/audit_context.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/rpc/context/audit_context.proto", :syntax => :proto3) do
    add_message "google.rpc.context.AuditContext" do
      optional :audit_log, :bytes, 1
      optional :scrubbed_request, :message, 2, "google.protobuf.Struct"
      optional :scrubbed_response, :message, 3, "google.protobuf.Struct"
      optional :scrubbed_response_item_count, :int32, 4
      optional :target_resource, :string, 5
    end
  end
end

module Google
  module Rpc
    module Context
      AuditContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.context.AuditContext").msgclass
    end
  end
end
