# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/drive/drive_addon_manifest.proto

require 'google/protobuf'

require 'google/apps/script/type/extension_point_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/apps/script/type/drive/drive_addon_manifest.proto", :syntax => :proto3) do
    add_message "google.apps.script.type.drive.DriveAddOnManifest" do
      optional :homepage_trigger, :message, 1, "google.apps.script.type.HomepageExtensionPoint"
      optional :on_items_selected_trigger, :message, 2, "google.apps.script.type.drive.DriveExtensionPoint"
    end
    add_message "google.apps.script.type.drive.DriveExtensionPoint" do
      optional :run_function, :string, 1
    end
  end
end

module Google
  module Apps
    module Script
      module Type
        module Drive
          DriveAddOnManifest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.drive.DriveAddOnManifest").msgclass
          DriveExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.drive.DriveExtensionPoint").msgclass
        end
      end
    end
  end
end
