# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/http.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/rpc/http.proto", :syntax => :proto3) do
    add_message "google.rpc.HttpRequest" do
      optional :method, :string, 1
      optional :uri, :string, 2
      repeated :headers, :message, 3, "google.rpc.HttpHeader"
      optional :body, :bytes, 4
    end
    add_message "google.rpc.HttpResponse" do
      optional :status, :int32, 1
      optional :reason, :string, 2
      repeated :headers, :message, 3, "google.rpc.HttpHeader"
      optional :body, :bytes, 4
    end
    add_message "google.rpc.HttpHeader" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
  end
end

module Google
  module Rpc
    HttpRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.HttpRequest").msgclass
    HttpResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.HttpResponse").msgclass
    HttpHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.rpc.HttpHeader").msgclass
  end
end
