# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/calendar/calendar_addon_manifest.proto

require 'google/protobuf'

require 'google/api/field_behavior_pb'
require 'google/apps/script/type/extension_point_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/apps/script/type/calendar/calendar_addon_manifest.proto", :syntax => :proto3) do
    add_message "google.apps.script.type.calendar.CalendarAddOnManifest" do
      optional :homepage_trigger, :message, 6, "google.apps.script.type.HomepageExtensionPoint"
      repeated :conference_solution, :message, 3, "google.apps.script.type.calendar.ConferenceSolution"
      optional :create_settings_url_function, :string, 5
      optional :event_open_trigger, :message, 10, "google.apps.script.type.calendar.CalendarExtensionPoint"
      optional :event_update_trigger, :message, 11, "google.apps.script.type.calendar.CalendarExtensionPoint"
      optional :current_event_access, :enum, 12, "google.apps.script.type.calendar.CalendarAddOnManifest.EventAccess"
    end
    add_enum "google.apps.script.type.calendar.CalendarAddOnManifest.EventAccess" do
      value :UNSPECIFIED, 0
      value :METADATA, 1
      value :READ, 3
      value :WRITE, 4
      value :READ_WRITE, 5
    end
    add_message "google.apps.script.type.calendar.ConferenceSolution" do
      optional :on_create_function, :string, 1
      optional :id, :string, 4
      optional :name, :string, 5
      optional :logo_url, :string, 6
    end
    add_message "google.apps.script.type.calendar.CalendarExtensionPoint" do
      optional :run_function, :string, 1
    end
  end
end

module Google
  module Apps
    module Script
      module Type
        module Calendar
          CalendarAddOnManifest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.calendar.CalendarAddOnManifest").msgclass
          CalendarAddOnManifest::EventAccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.calendar.CalendarAddOnManifest.EventAccess").enummodule
          ConferenceSolution = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.calendar.ConferenceSolution").msgclass
          CalendarExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.calendar.CalendarExtensionPoint").msgclass
        end
      end
    end
  end
end
