# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backstory/data_access.proto

require 'google/protobuf'


descriptor_data = "\n\x1b\x62\x61\x63kstory/data_access.proto\x12\x10google.backstory\"6\n\x18\x44\x61taAccessIngestionLabel\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xd4\x01\n\x10\x44\x61taAccessLabels\x12\x11\n\tlog_types\x18\x01 \x03(\t\x12\x1c\n\x10ingestion_labels\x18\x02 \x03(\tB\x02\x18\x01\x12\x12\n\nnamespaces\x18\x03 \x03(\t\x12\x15\n\rcustom_labels\x18\x04 \x03(\t\x12G\n\x13ingestion_kv_labels\x18\x05 \x03(\x0b\x32*.google.backstory.DataAccessIngestionLabel\x12\x1b\n\x13\x61llow_scoped_access\x18\x06 \x01(\x08\x42\x89\x01\n\x14\x63om.google.backstoryP\x01Z5cloud.google.com/go/backstory/backstorypb;backstorypb\xaa\x02\x10Google.Backstory\xca\x02\x10Google\\Backstory\xea\x02\x11Google::Backstoryb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Backstory
    DataAccessIngestionLabel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.backstory.DataAccessIngestionLabel").msgclass
    DataAccessLabels = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.backstory.DataAccessLabels").msgclass
  end
end

#### Source proto file: backstory/data_access.proto ####
#
# // Copyright 2026 Google LLC
# //
# // Licensed under the Apache License, Version 2.0 (the "License");
# // you may not use this file except in compliance with the License.
# // You may obtain a copy of the License at
# //
# //     http://www.apache.org/licenses/LICENSE-2.0
# //
# // Unless required by applicable law or agreed to in writing, software
# // distributed under the License is distributed on an "AS IS" BASIS,
# // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# // See the License for the specific language governing permissions and
# // limitations under the License.
#
# syntax = "proto3";
#
# package google.backstory;
#
# option csharp_namespace = "Google.Backstory";
# option go_package = "cloud.google.com/go/backstory/backstorypb;backstorypb";
# option java_multiple_files = true;
# option java_package = "com.google.backstory";
# option php_namespace = "Google\\Backstory";
# option ruby_package = "Google::Backstory";
#
# // Label used in data access for ingestion.
# message DataAccessIngestionLabel {
#   // The key.
#   string key = 1;
#
#   // The value.
#   string value = 2;
# }
#
# // Label used in data access.
# message DataAccessLabels {
#   // All the LogType labels.
#   repeated string log_types = 1;
#
#   // All the ingestion labels.
#   repeated string ingestion_labels = 2 [deprecated = true];
#
#   // All the namespaces.
#   repeated string namespaces = 3;
#
#   // All the complex labels (UDM search syntax based).
#   repeated string custom_labels = 4;
#
#   // All the ingestion labels (key/value pairs).
#   repeated DataAccessIngestionLabel ingestion_kv_labels = 5;
#
#   // Are the labels ready for scoped access
#   bool allow_scoped_access = 6;
# }
