# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backstory/id.proto

require 'google/protobuf'


descriptor_data = "\n\x12\x62\x61\x63kstory/id.proto\x12\x10google.backstory\"\x9e\x02\n\x02Id\x12\x31\n\tnamespace\x18\x01 \x01(\x0e\x32\x1e.google.backstory.Id.Namespace\x12\n\n\x02id\x18\x02 \x01(\x0c\x12\x11\n\tstring_id\x18\x03 \x01(\t\"\xc5\x01\n\tNamespace\x12\x18\n\x14NORMALIZED_TELEMETRY\x10\x00\x12\x11\n\rRAW_TELEMETRY\x10\x01\x12\x13\n\x0fRULE_DETECTIONS\x10\x02\x12\r\n\tUPPERCASE\x10\x03\x12\x18\n\x14MACHINE_INTELLIGENCE\x10\x04\x12\x1b\n\x17SECURITY_COMMAND_CENTER\x10\x05\x12\x0f\n\x0bUNSPECIFIED\x10\x06\x12\x0e\n\nSOAR_ALERT\x10\x07\x12\x0f\n\x0bVIRUS_TOTAL\x10\x08\x42\x89\x01\n\x14\x63om.google.backstoryP\x01Z5cloud.google.com/go/backstory/backstorypb;backstorypb\xaa\x02\x10Google.Backstory\xca\x02\x10Google\\Backstory\xea\x02\x11Google::Backstoryb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Backstory
    Id = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.backstory.Id").msgclass
    Id::Namespace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.backstory.Id.Namespace").enummodule
  end
end

#### Source proto file: backstory/id.proto ####
#
# // Copyright 2026 Google LLC
# //
# // Licensed under the Apache License, Version 2.0 (the "License");
# // you may not use this file except in compliance with the License.
# // You may obtain a copy of the License at
# //
# //     http://www.apache.org/licenses/LICENSE-2.0
# //
# // Unless required by applicable law or agreed to in writing, software
# // distributed under the License is distributed on an "AS IS" BASIS,
# // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# // See the License for the specific language governing permissions and
# // limitations under the License.
#
# syntax = "proto3";
#
# package google.backstory;
#
# option csharp_namespace = "Google.Backstory";
# option go_package = "cloud.google.com/go/backstory/backstorypb;backstorypb";
# option java_multiple_files = true;
# option java_package = "com.google.backstory";
# option php_namespace = "Google\\Backstory";
# option ruby_package = "Google::Backstory";
#
# // Identifier to identify a UDM object like a UDM event, Entity, Collection.
# // The full identifier for persistence is created by setting the 32 most
# // significant bits as the Id.Namespace enum This is a convenience wrapper to
# // define the id space enum values and provide an easy interface for RPCs, most
# // persistence use cases should use a denormalized form.
# message Id {
#   // Extracted Namespace Component
#   enum Namespace {
#     // Ingested and Normalized telemetry events
#     NORMALIZED_TELEMETRY = 0;
#
#     // Ingested Raw telemetry
#     RAW_TELEMETRY = 1;
#
#     // Chronicle Rules engine
#     RULE_DETECTIONS = 2;
#
#     // Uppercase
#     UPPERCASE = 3;
#
#     // DSML - Machine Intelligence
#     MACHINE_INTELLIGENCE = 4;
#
#     // A normalized telemetry event from Google Security Command Center.
#     SECURITY_COMMAND_CENTER = 5;
#
#     // Unspecified Namespace
#     UNSPECIFIED = 6;
#
#     // An alert coming from other SIEMs via Chronicle SOAR.
#     SOAR_ALERT = 7;
#
#     // VirusTotal.
#     VIRUS_TOTAL = 8;
#   }
#
#   // Namespace the id belongs to.
#   Namespace namespace = 1;
#
#   // Full raw ID.
#   bytes id = 2;
#
#   // Some ids are stored as strings that are not able to be translated to bytes,
#   // so store these separately.
#   // Ex. detection id of the form de_aaaaaaaa-aaaa...
#   string string_id = 3;
# }
