# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/interval.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/type/interval.proto", :syntax => :proto3) do
    add_message "google.type.Interval" do
      optional :start_time, :message, 1, "google.protobuf.Timestamp"
      optional :end_time, :message, 2, "google.protobuf.Timestamp"
    end
  end
end

module Google
  module Type
    Interval = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.type.Interval").msgclass
  end
end
