# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/localized_text.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/type/localized_text.proto", :syntax => :proto3) do
    add_message "google.type.LocalizedText" do
      optional :text, :string, 1
      optional :language_code, :string, 2
    end
  end
end

module Google
  module Type
    LocalizedText = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.type.LocalizedText").msgclass
  end
end
