# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/addon_widget_set.proto

require 'google/protobuf'


descriptor_data = "\n.google/apps/script/type/addon_widget_set.proto\x12\x17google.apps.script.type\"\xa4\x02\n\x0e\x41\x64\x64OnWidgetSet\x12H\n\x0cused_widgets\x18\x01 \x03(\x0e\x32\x32.google.apps.script.type.AddOnWidgetSet.WidgetType\"\xc7\x01\n\nWidgetType\x12\x1b\n\x17WIDGET_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x44\x41TE_PICKER\x10\x01\x12\x12\n\x0eSTYLED_BUTTONS\x10\x02\x12\x14\n\x10PERSISTENT_FORMS\x10\x03\x12\x10\n\x0c\x46IXED_FOOTER\x10\x04\x12!\n\x1dUPDATE_SUBJECT_AND_RECIPIENTS\x10\x05\x12\x0f\n\x0bGRID_WIDGET\x10\x06\x12\x1b\n\x17\x41\x44\x44ON_COMPOSE_UI_ACTION\x10\x07\x42\xbd\x01\n\x1b\x63om.google.apps.script.typeB\x13\x41\x64\x64OnWidgetSetProtoP\x01Z6google.golang.org/genproto/googleapis/apps/script/type\xaa\x02\x17Google.Apps.Script.Type\xca\x02\x17Google\\Apps\\Script\\Type\xea\x02\x1aGoogle::Apps::Script::Typeb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Apps
    module Script
      module Type
        AddOnWidgetSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.AddOnWidgetSet").msgclass
        AddOnWidgetSet::WidgetType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.AddOnWidgetSet.WidgetType").enummodule
      end
    end
  end
end
