# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/extension_point.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'


descriptor_data = "\n-google/apps/script/type/extension_point.proto\x12\x17google.apps.script.type\x1a\x1egoogle/protobuf/wrappers.proto\"O\n\x16MenuItemExtensionPoint\x12\x14\n\x0crun_function\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08logo_url\x18\x03 \x01(\t\"[\n\x16HomepageExtensionPoint\x12\x14\n\x0crun_function\x18\x01 \x01(\t\x12+\n\x07\x65nabled\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"j\n\x1dUniversalActionExtensionPoint\x12\r\n\x05label\x18\x01 \x01(\t\x12\x13\n\topen_link\x18\x02 \x01(\tH\x00\x12\x16\n\x0crun_function\x18\x03 \x01(\tH\x00\x42\r\n\x0b\x61\x63tion_typeB\xa8\x01\n\x1b\x63om.google.apps.script.typeP\x01Z6google.golang.org/genproto/googleapis/apps/script/type\xaa\x02\x17Google.Apps.Script.Type\xca\x02\x17Google\\Apps\\Script\\Type\xea\x02\x1aGoogle::Apps::Script::Typeb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Apps
    module Script
      module Type
        MenuItemExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.MenuItemExtensionPoint").msgclass
        HomepageExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.HomepageExtensionPoint").msgclass
        UniversalActionExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.UniversalActionExtensionPoint").msgclass
      end
    end
  end
end

#### Source proto file: google/apps/script/type/extension_point.proto ####
#
# // Copyright 2024 Google LLC
# //
# // Licensed under the Apache License, Version 2.0 (the "License");
# // you may not use this file except in compliance with the License.
# // You may obtain a copy of the License at
# //
# //     http://www.apache.org/licenses/LICENSE-2.0
# //
# // Unless required by applicable law or agreed to in writing, software
# // distributed under the License is distributed on an "AS IS" BASIS,
# // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# // See the License for the specific language governing permissions and
# // limitations under the License.
#
# syntax = "proto3";
#
# package google.apps.script.type;
#
# import "google/protobuf/wrappers.proto";
#
# option csharp_namespace = "Google.Apps.Script.Type";
# option go_package = "google.golang.org/genproto/googleapis/apps/script/type";
# option java_multiple_files = true;
# option java_package = "com.google.apps.script.type";
# option php_namespace = "Google\\Apps\\Script\\Type";
# option ruby_package = "Google::Apps::Script::Type";
#
# // Common Manifest protos for G Suite extension-point configuration.
#
# // Common format for declaring a  menu item, or button, that appears within a
# // host app.
# message MenuItemExtensionPoint {
#   // Required. The endpoint to execute when this extension point is
#   // activated.
#   string run_function = 1;
#
#   // Required. User-visible text describing the action taken by activating this
#   // extension point. For example, "Insert invoice".
#   string label = 2;
#
#   // The URL for the logo image shown in the add-on toolbar.
#   //
#   // If not set, defaults to the add-on's primary logo URL.
#   string logo_url = 3;
# }
#
# // Common format for declaring an add-on's home-page view.
# message HomepageExtensionPoint {
#   // Required. The endpoint to execute when this extension point is
#   // activated.
#   string run_function = 1;
#
#   // Optional. If set to `false`, disable the home-page view in this context.
#   //
#   // Defaults to `true` if unset.
#   //
#   // If an add-ons custom home-page view is disabled, an autogenerated overview
#   // card will be provided for users instead.
#   google.protobuf.BoolValue enabled = 2;
# }
#
# // Format for declaring a universal action menu item extension point.
# message UniversalActionExtensionPoint {
#   // Required. User-visible text describing the action taken by activating this
#   // extension point, for example, "Add a new contact".
#   string label = 1;
#
#   // Required. The action type supported on a universal action menu item. It
#   // could be either a link to open or an endpoint to execute.
#   oneof action_type {
#     // URL to be opened by the UniversalAction.
#     string open_link = 2;
#
#     // Endpoint to be run by the UniversalAction.
#     string run_function = 3;
#   }
# }
