# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/extension_point.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/apps/script/type/extension_point.proto", :syntax => :proto3) do
    add_message "google.apps.script.type.MenuItemExtensionPoint" do
      optional :run_function, :string, 1
      optional :label, :string, 2
      optional :logo_url, :string, 3
    end
    add_message "google.apps.script.type.HomepageExtensionPoint" do
      optional :run_function, :string, 1
      optional :enabled, :message, 2, "google.protobuf.BoolValue"
    end
    add_message "google.apps.script.type.UniversalActionExtensionPoint" do
      optional :label, :string, 1
      oneof :action_type do
        optional :open_link, :string, 2
        optional :run_function, :string, 3
      end
    end
  end
end

module Google
  module Apps
    module Script
      module Type
        MenuItemExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.MenuItemExtensionPoint").msgclass
        HomepageExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.HomepageExtensionPoint").msgclass
        UniversalActionExtensionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.UniversalActionExtensionPoint").msgclass
      end
    end
  end
end
