# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/script/type/script_manifest.proto

require 'google/protobuf'

require 'google/apps/script/type/addon_widget_set_pb'
require 'google/apps/script/type/extension_point_pb'
require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/apps/script/type/script_manifest.proto", :syntax => :proto3) do
    add_message "google.apps.script.type.CommonAddOnManifest" do
      optional :name, :string, 1
      optional :logo_url, :string, 2
      optional :layout_properties, :message, 3, "google.apps.script.type.LayoutProperties"
      optional :add_on_widget_set, :message, 4, "google.apps.script.type.AddOnWidgetSet"
      optional :use_locale_from_app, :bool, 5
      optional :homepage_trigger, :message, 6, "google.apps.script.type.HomepageExtensionPoint"
      repeated :universal_actions, :message, 7, "google.apps.script.type.UniversalActionExtensionPoint"
      optional :open_link_url_prefixes, :message, 8, "google.protobuf.ListValue"
    end
    add_message "google.apps.script.type.LayoutProperties" do
      optional :primary_color, :string, 1
      optional :secondary_color, :string, 2
    end
    add_message "google.apps.script.type.HttpOptions" do
      optional :authorization_header, :enum, 1, "google.apps.script.type.HttpAuthorizationHeader"
    end
    add_enum "google.apps.script.type.HttpAuthorizationHeader" do
      value :HTTP_AUTHORIZATION_HEADER_UNSPECIFIED, 0
      value :SYSTEM_ID_TOKEN, 1
      value :USER_ID_TOKEN, 2
      value :NONE, 3
    end
  end
end

module Google
  module Apps
    module Script
      module Type
        CommonAddOnManifest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.CommonAddOnManifest").msgclass
        LayoutProperties = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.LayoutProperties").msgclass
        HttpOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.HttpOptions").msgclass
        HttpAuthorizationHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.apps.script.type.HttpAuthorizationHeader").enummodule
      end
    end
  end
end
