# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/extended_operations.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/cloud/extended_operations.proto", :syntax => :proto3) do
    add_enum "google.cloud.OperationResponseMapping" do
      value :UNDEFINED, 0
      value :NAME, 1
      value :STATUS, 2
      value :ERROR_CODE, 3
      value :ERROR_MESSAGE, 4
    end
  end
end

module Google
  module Cloud
    OperationResponseMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.OperationResponseMapping").enummodule
  end
end
