source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gemspec

gem "googleapis-common-protos", path: "../googleapis-common-protos"
gem "googleapis-common-protos-types", path: "../googleapis-common-protos-types"
