# frozen_string_literal: true

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'bundler/gem_tasks'

# Perform post-compile steps on a couple of protos to install backward
# compatibility aliases.
def postprocess_protos
  File.open "#{__dir__}/lib/google/logging/type/http_request_pb.rb", "a" do |file|
    file.puts "\nmodule Google\n  module Logging\n    module Type\n      HttpRequest = ::Google::Cloud::Logging::Type::HttpRequest\n    end\n  end\nend"
  end
  File.open "#{__dir__}/lib/google/logging/type/log_severity_pb.rb", "a" do |file|
    file.puts "\nmodule Google\n  module Logging\n    module Type\n      LogSeverity = ::Google::Cloud::Logging::Type::LogSeverity\n    end\n  end\nend"
  end
end

desc "Compile the necessary protobuf files."
task :compile_protos do
  Rake::Task[:clean_protos].invoke
  FileUtils.mkdir 'lib'

  protos = [
    "../googleapis/google/api/*.proto",
    "../googleapis/google/logging/type/*.proto",
    "../googleapis/google/longrunning/*.proto",
    "../googleapis/google/rpc/*.proto",
    "../googleapis/google/type/*.proto",
  ]

  command = []
  command << "grpc_tools_ruby_protoc"
  command << "--ruby_out=lib"
  command << "-I ../googleapis"
  command += protos
  full_command = command.join " "

  puts full_command
  system full_command

  postprocess_protos
end

desc "Test loading all proto files"
task :test_loading do
  puts "\nLoading proto files"
  Dir.glob("lib/google/**/*_pb.rb") do |path|
    puts path
    require_relative path
  end
end

desc "Remove the compiled protos."
task :clean_protos do
  FileUtils.rm_rf "lib"
end

desc "Run the CI build"
task :ci do
  puts "\nCompiling Protos"
  Rake::Task[:compile_protos].invoke
  Rake::Task[:test_loading].invoke
end

Rake::Task[:build].enhance [:compile_protos]
Rake::Task[:clean].enhance [:clean_protos]

task default: :ci