name: "CI"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    if: ${{ github.repository == 'googleapis/common-protos-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.2"
          - os: ubuntu-latest
            ruby: "3.3"
          - os: ubuntu-latest
            ruby: "3.4"
          - os: ubuntu-latest
            ruby: "4.0"
          - os: macos-latest
            ruby: "4.0"
          - os: windows-latest
            ruby: "4.0"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Checkout submodules
        run: |
          git submodule update --init
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          toys ci -v --build --test --github-event-name="$GITHUB_EVENT_NAME" --github-event-payload="$GITHUB_EVENT_PATH"
