name: "CI"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    if: ${{ github.repository == 'googleapis/common-protos-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.2"
          - os: ubuntu-latest
            ruby: "3.3"
          - os: ubuntu-latest
            ruby: "3.4"
          - os: ubuntu-latest
            ruby: "4.0"
          - os: macos-latest
            ruby: "4.0"
          - os: windows-latest
            ruby: "4.0"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Checkout submodules
        run: |
          git submodule update --init
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          toys ci -v --build --test --github-event-name="$GITHUB_EVENT_NAME" --github-event-payload="$GITHUB_EVENT_PATH"
